[project]
name = "tictactoe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mock>=5.2.0",
    "numpy>=2.2.6",
    "pydantic>=2.11.5",
    "pytest>=8.4.1",
]
